import fs from 'fs';
import path from 'path';
import { format, parse, isValid } from 'date-fns';
import type { JournalEntry, GitChange, SearchOptions } from '../types.js';
import { loadConfig, findConfigDir } from './config.js';

export interface WeekSummaryEntry {
  date: string;
  summary: string;
}

export interface WeekSummaryResult {
  weekStart: string;
  weekEnd: string;
  summary: string;
  entries: WeekSummaryEntry[];
}

export function getJournalPath(date: string): string {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found. Run `memory-lane init` first.');
  }
  const config = loadConfig(configDir);
  return path.join(configDir, config.journalDir, `${date}.md`);
}

export function journalExists(date: string): boolean {
  try {
    const journalPath = getJournalPath(date);
    return fs.existsSync(journalPath);
  } catch {
    return false;
  }
}

export function appendEntry(entry: JournalEntry): void {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found. Run `memory-lane init` first.');
  }
  const config = loadConfig(configDir);

  const journalDir = path.join(configDir, config.journalDir);
  if (!fs.existsSync(journalDir)) {
    fs.mkdirSync(journalDir, { recursive: true });
  }

  const journalPath = path.join(journalDir, `${entry.date}.md`);

  // Check if entry already exists for today (dedup)
  if (fs.existsSync(journalPath)) {
    const existing = fs.readFileSync(journalPath, 'utf-8');
    // Simple dedup: if we already have a summary for today, skip
    if (existing.includes('_Generated by MemoryLane')) {
      console.log(`Journal entry for ${entry.date} already exists. Skipping.`);
      return;
    }
  }

  const content = formatEntry(entry);
  fs.appendFileSync(journalPath, content, 'utf-8');
  console.log(`Journal entry written to ${journalPath}`);
}

function formatEntry(entry: JournalEntry): string {
  const changeList = entry.changes.length > 0
    ? entry.changes.map(c => `  - \`${c.file}\` — ${c.status}`).join('\n')
    : '  (no file changes detected)';

  return `## ${entry.date}

**Summary:** ${entry.summary}

**Changes:**
${changeList}

_Generated by MemoryLane at ${entry.generatedAt}_\n`;
}

export function searchJournal(query: string, options: SearchOptions = {}): Array<{ date: string; line: string; lineNum: number }> {
  const { from, to } = options;


  const results: Array<{ date: string; line: string; lineNum: number }> = [];
  const configDir = findConfigDir();
  if (!configDir) {
    return [];
  }
  const config = loadConfig(configDir);
  const journalDir = path.join(configDir, config.journalDir);

  if (!fs.existsSync(journalDir)) {
    return [];
  }

  const regex = new RegExp(query, 'i');
  const files = fs.readdirSync(journalDir).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const fileDate = file.replace('.md', '');
    // Filter by date range if specified
    if (from && fileDate < from) continue;
    if (to && fileDate > to) continue;

    const filePath = path.join(journalDir, file);
    const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
    lines.forEach((line, idx) => {
      if (regex.test(line)) {
        results.push({ date: fileDate, line: line.trim(), lineNum: idx + 1 });
      }
    });
  }

  return results;
}

export function initJournalDir(dir: string, journalDir: string): void {
  const fullPath = path.join(dir, journalDir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
  }
  // Create a .gitkeep to ensure directory is tracked
  const gitkeep = path.join(fullPath, '.gitkeep');
  if (!fs.existsSync(gitkeep)) {
    fs.writeFileSync(gitkeep, '', 'utf-8');
  }
}

export function getWeekEntries(weekStart: string, weekEnd: string): WeekSummaryEntry[] {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found.');
  }
  const config = loadConfig(configDir);
  const journalDir = path.join(configDir, config.journalDir);

  if (!fs.existsSync(journalDir)) {
    return [];
  }

  const entries: WeekSummaryEntry[] = [];
  const files = fs.readdirSync(journalDir).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const fileDate = file.replace('.md', '');
    if (fileDate >= weekStart && fileDate <= weekEnd) {
      const content = fs.readFileSync(path.join(journalDir, file), 'utf-8');
      // Extract the summary line: **Summary:** <text>
      const summaryMatch = content.match(/\*\*Summary:\*\*\s*(.+)/);
      if (summaryMatch) {
        entries.push({ date: fileDate, summary: summaryMatch[1].trim() });
      }
    }
  }

  // Sort by date ascending
  entries.sort((a, b) => a.date.localeCompare(b.date));
  return entries;
}

export function writeWeekSummary(result: WeekSummaryResult): void {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found.');
  }
  const config = loadConfig(configDir);

  const journalDir = path.join(configDir, config.journalDir);
  if (!fs.existsSync(journalDir)) {
    fs.mkdirSync(journalDir, { recursive: true });
  }

  const weekFileName = `${result.weekStart}.md`;
  const weekFilePath = path.join(journalDir, weekFileName);

  // Group entries by date and show per-day count
  const byDate = new Map<string, string[]>();
  for (const e of result.entries) {
    if (!byDate.has(e.date)) byDate.set(e.date, []);
    byDate.get(e.date)!.push(e.summary);
  }

  const dayEntries = Array.from(byDate.entries())
    .map(([date, summaries]) => {
      const count = summaries.length;
      const summary = count === 1 ? summaries[0] : summaries.join('; ');
      return `- **${date} (${count} ${count === 1 ? 'entry' : 'entries'}):** ${summary}`;
    })
    .join('\n');

  const content = `# Week of ${result.weekStart} — ${result.weekEnd}

**Weekly Summary:** ${result.summary}

## Daily Entries
${dayEntries}

_Generated by MemoryLane on ${format(new Date(), 'yyyy-MM-dd')}_
`;

  fs.writeFileSync(weekFilePath, content, 'utf-8');
  console.log(`Weekly summary written to ${weekFilePath}`);
}