import fs from 'fs';
import path from 'path';
import { format } from 'date-fns';
import type { JournalEntry, GitChange } from '../types.js';
import { loadConfig, findConfigDir } from './config.js';

export function getJournalPath(date: string): string {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found. Run `memory-lane init` first.');
  }
  const config = loadConfig(configDir);
  return path.join(configDir, config.journalDir, `${date}.md`);
}

export function journalExists(date: string): boolean {
  try {
    const journalPath = getJournalPath(date);
    return fs.existsSync(journalPath);
  } catch {
    return false;
  }
}

export function appendEntry(entry: JournalEntry): void {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found. Run `memory-lane init` first.');
  }
  const config = loadConfig(configDir);

  const journalDir = path.join(configDir, config.journalDir);
  if (!fs.existsSync(journalDir)) {
    fs.mkdirSync(journalDir, { recursive: true });
  }

  const journalPath = path.join(journalDir, `${entry.date}.md`);

  // Check if entry already exists for today (dedup)
  if (fs.existsSync(journalPath)) {
    const existing = fs.readFileSync(journalPath, 'utf-8');
    // Simple dedup: if we already have a summary for today, skip
    if (existing.includes('_Generated by MemoryLane')) {
      console.log(`Journal entry for ${entry.date} already exists. Skipping.`);
      return;
    }
  }

  const content = formatEntry(entry);
  fs.appendFileSync(journalPath, content, 'utf-8');
  console.log(`Journal entry written to ${journalPath}`);
}

function formatEntry(entry: JournalEntry): string {
  const changeList = entry.changes.length > 0
    ? entry.changes.map(c => `  - \`${c.file}\` — ${c.status}`).join('\n')
    : '  (no file changes detected)';

  return `## ${entry.date}

**Summary:** ${entry.summary}

**Changes:**
${changeList}

_Generated by MemoryLane at ${entry.generatedAt}_\n`;
}

export function searchJournal(query: string): Array<{ date: string; line: string; lineNum: number }> {
  const configDir = findConfigDir();
  if (!configDir) {
    throw new Error('No .memorylanerc found. Run `memory-lane init` first.');
  }
  const config = loadConfig(configDir);
  const journalDir = path.join(configDir, config.journalDir);

  if (!fs.existsSync(journalDir)) {
    return [];
  }

  const results: Array<{ date: string; line: string; lineNum: number }> = [];
  const files = fs.readdirSync(journalDir).filter(f => f.endsWith('.md'));

  const regex = new RegExp(query, 'i');
  for (const file of files) {
    const filePath = path.join(journalDir, file);
    const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
    lines.forEach((line, idx) => {
      if (regex.test(line)) {
        results.push({ date: file.replace('.md', ''), line: line.trim(), lineNum: idx + 1 });
      }
    });
  }

  return results;
}

export function initJournalDir(dir: string, journalDir: string): void {
  const fullPath = path.join(dir, journalDir);
  if (!fs.existsSync(fullPath)) {
    fs.mkdirSync(fullPath, { recursive: true });
  }
  // Create a .gitkeep to ensure directory is tracked
  const gitkeep = path.join(fullPath, '.gitkeep');
  if (!fs.existsSync(gitkeep)) {
    fs.writeFileSync(gitkeep, '', 'utf-8');
  }
}